name: sprite_2_dart
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:
  http: ^1.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.24.0
