name: sbb_maps_example
description: Example app for the sbb_maps_flutter package.
publish_to: "none"
version: 0.0.9+9000

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  sbb_maps_flutter:
    path: ../

  design_system_flutter:
    git:
      url: https://github.com/SchweizerischeBundesbahnen/design_system_flutter.git
      ref: 2.0.0
  envied: ^0.5.4
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  envied_generator: ^0.5.4
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/custom_icons/
